"use client";

import { useMemo, useState } from "react";

type Camera={name:string;codec:string;hours:number;rate:number};
const rates:Record<string,number>={"ProRes 422":110,"ProRes 422 HQ":165,"ProRes 4444":330,"H.264":25,"H.265":18,"BRAW Q5":75,"ARRIRAW":300};

function gb(n:number){return n>=1000?`${(n/1000).toFixed(1)} TB`:`${n.toFixed(0)} GB`}
function App(){
 const [days,setDays]=useState(5); const [working,setWorking]=useState(4); const [backup,setBackup]=useState(2); const [shuttle,setShuttle]=useState(2);
 const [cams,setCams]=useState<Camera[]>([{name:"A-Cam",codec:"ProRes 422 HQ",hours:3,rate:165},{name:"B-Cam",codec:"ProRes 422",hours:2,rate:110}]);
 const daily=cams.reduce((s,c)=>s+c.hours*c.rate,0); const project=daily*days;
 const total=working+backup+shuttle;
 const systems=useMemo(()=>[
  {name:"Balanced / Best Value",score:94,drive:`${Math.ceil(project/1000)} TB Working + ${Math.ceil(project*backup/1000)} TB Backup`,why:"속도·안전·비용의 균형"},
  {name:"Performance",score:91,drive:`${Math.ceil(project/750)} TB NVMe Working + ${Math.ceil(project*backup/1000)} TB Backup`,why:"고속 백업과 멀티카드 동시 처리"},
  {name:"Safety First",score:88,drive:`${Math.ceil(project/1000)} TB Working + ${Math.ceil(project*2/1000)} TB 이중 Backup`,why:"현장 데이터 손실 리스크 최소화"}
 ],[project,backup]);
 const add=()=>setCams([...cams,{name:`${String.fromCharCode(65+cams.length)}-Cam`,codec:"ProRes 422",hours:2,rate:110}]);
 const exportPlan=()=>{const plan={project:{days,cameras:cams,dailyGB:daily,projectGB:project},storage:{workingTB:working,backupTB:backup,shuttleTB:shuttle},recommendations:systems};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:"application/json"}));a.download="dit-plan.json";a.click()};
 return <div className="app"><header className="top"><div className="brand">DIT <span>WORKFLOW TOOLKIT</span></div><small>Workflow-first system planner · MVP</small></header><main className="wrap"><div className="grid"><aside className="panel"><h2>01 · Project Setup</h2><div className="field"><label>SHOOTING DAYS</label><input className="input" type="number" min="1" value={days} onChange={e=>setDays(+e.target.value||1)}/></div><div className="section"><div className="sectionhead"><h2>02 · Shooting Profile</h2><button className="btn" onClick={add}>+ Camera</button></div>{cams.map((c,i)=><div className="field" key={i}><div className="row"><input className="input" value={c.name} onChange={e=>{const x=[...cams];x[i]={...x[i],name:e.target.value};setCams(x)}}/><select className="select" value={c.codec} onChange={e=>{const x=[...cams];x[i]={...x[i],codec:e.target.value,rate:rates[e.target.value]};setCams(x)}}>{Object.keys(rates).map(r=><option key={r}>{r}</option>)}</select><input className="input" type="number" step=".5" min="0" value={c.hours} onChange={e=>{const x=[...cams];x[i]={...x[i],hours:+e.target.value||0};setCams(x)}}/><button className="btn danger" onClick={()=>setCams(cams.filter((_,j)=>j!==i))}>×</button></div><div className="muted">Estimated Camera Roll Time · {c.rate} MB/s</div></div>)}</div><div className="section"><h2>03 · Storage Target</h2>{[["Working Drive",working,setWorking],["Backup Drive",backup,setBackup],["Shuttle Drive",shuttle,setShuttle]].map(([n,v,set],i)=><div className="field" key={i}><label>{n.toString().toUpperCase()}</label><input className="input" type="number" min="0" step=".5" value={v as number} onChange={e=>(set as any)(+e.target.value||0)}/></div>)}</div><button className="btn primary" style={{width:"100%",marginTop:8}} onClick={exportPlan}>Export DIT Plan JSON</button></aside>
 <section><div className="panel"><div className="sectionhead"><div><h2>Project Data Requirement</h2><div className="muted">Data is calculated automatically from recording rate × actual REC time × camera count.</div></div><span className="badge">AUTO</span></div><div className="stats"><div className="stat"><span className="muted">DAILY DATA</span><b>{gb(daily)}</b></div><div className="stat"><span className="muted">PROJECT DATA</span><b>{gb(project)}</b></div><div className="stat"><span className="muted">STORAGE TARGET</span><b>{total} TB</b></div></div></div><div className="panel section"><h2>Workflow Requirement</h2><div className="flow">{[["MEDIA","Camera Cards"],["INGEST","Card Reader"],["WORK","Working Drive"],["BACKUP","Backup × 2"],["VERIFY","Checksum"],["SHUTTLE","Client / Post"]].map(x=><div className="node" key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></div>)}</div></div><div className="section"><div className="sectionhead"><h2>System Recommendations</h2><span className="badge">CONSTRAINT + SCORE</span></div><div className="cards">{systems.map((s,i)=><div className={`card ${i===0?"best":""}`} key={s.name}><div className="muted">OPTION {i+1}</div><h3>{s.name}</h3><div className="score">{s.score}<small style={{fontSize:13,color:"#87919e"}}>/100</small></div><div className="meter"><i style={{width:`${s.score}%`}}/></div><p className="muted">{s.why}</p><ul className="list"><li>{s.drive}</li><li>10GbE / USB-C workflow</li><li>Checksum verification</li></ul></div>)}</div></div><div className="panel section"><div className="sectionhead"><h2>Compatibility & Bottlenecks</h2><span className="badge">NEXT ENGINE</span></div><p className="muted">Hard constraints: storage capacity, sustained write speed, ports/protocols, power and budget. Production DB will validate each connection as a graph.</p></div><div className="panel section"><div className="sectionhead"><h2>Auto Cable & Accessory BOM</h2><span className="badge">AUTO</span></div><div className="bom"><div>USB-C 10Gbps · Card Reader → Working Drive</div><div>USB-C / Thunderbolt · Working → Backup</div><div>AC power / PD adapters · Drive stack</div><div>Checksum / verification station · Accessories</div></div></div><div className="footer">DIT Workflow Toolkit · deterministic recommendation engine · product specs and prices should be source-verified before production use.</div></section></div></main></div>
}
export default App;
